name: Aqua Scanner
on:
  workflow_call:
    inputs:
      AQUA_URL:
        description: "Aqua URL"
        type: string
        default: "https://api.supply-chain.cloud.aquasec.com"
      CSPM_URL:
        description: "CSPM URL"
        type: string
        default: "https://api.cloudsploit.com"
      REGISTRY_NAME:
        description: "Registry to fetch the image from"
        type: string
        default: "docker.io"
      ARTIFACT_PATH:
        description: "artifact path"
        type: string
    secrets:
      AQUA_KEY:
        description: "Aqua Key"
        required: true
      AQUA_SECRET:
        description: "Aqua Secret"
        required: true
      GH_TOKEN:
        description: "GitHub token"
        required: true
      DOCKERHUB_USERNAME:
        description: "dockerhub username"
        required: true
      DOCKERHUB_TOKEN:
        description: "dockerhub access token"
        required: true
jobs:
  aqua:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.REGISTRY_NAME }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Manifest Generation
        run: |
          export BILLY_SERVER=https://billy.codesec.aquasec.com
          curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
          curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
          if ! cat install.sh.checksum | sha256sum ; then
          echo "install.sh checksum failed"
          exit 1
          fi
          BINDIR="." sh install.sh
          rm install.sh install.sh.checksum
          ./billy generate \
            --access-token "${{ secrets.GH_TOKEN }}" \
            --aqua-key "${{ secrets.AQUA_KEY }}" \
            --aqua-secret "${{ secrets.AQUA_SECRET }}" \
            --artifact-path "${{ inputs.REGISTRY_NAME }}/${{inputs.ARTIFACT_PATH}}"
        env:
          AQUA_URL: ${{ inputs.AQUA_URL }}
          CSPM_URL: ${{ inputs.CSPM_URL }}
